//
// Created by Calamari Yeste on 2024-07-06.
//

#ifndef RUST_STYLE_C_N_STD_COLLECTIONS_SETS_HASHMAP_H
#define RUST_STYLE_C_N_STD_COLLECTIONS_SETS_HASHMAP_H

typedef struct {

} HashMap;

#endif //RUST_STYLE_C_N_STD_COLLECTIONS_SETS_HASHMAP_H
